chore: all numbered

diff --git a/.github/workflows/build-deploy-nox.yaml b/.github/workflows/build-deploy-nox.yaml
--- a/.github/workflows/build-deploy-nox.yaml
+++ b/.github/workflows/build-deploy-nox.yaml
@@ -35,7 +35,7 @@ on:
         required: false
         type: number
         default: 0
-      nox_env_name:
+      nox_env_1_name:
         required: false
         type: string
         default: default_1
@@ -90,7 +90,7 @@ on:
         required: true
       DEPENDABOT_SLACK_WEBHOOK_URL:
         required: false
-      NOX_ENV_VALUE:
+      NOX_ENV_1_VALUE:
         required: false
       NOX_ENV_2_VALUE:
         required: false
@@ -106,7 +106,6 @@ jobs:
     env:
       notify_all: ''
       slack_webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
-      nox_env: ${{ inputs.nox_env }}
 
     steps:
       - name: Checkout
@@ -226,163 +225,161 @@ jobs:
         run: sudo sysctl -w vm.max_map_count=262144
 
       - name: Run tests with nox and no input variables
-        if: ${{ env.nox_env == 0 }}
+        if: ${{ inputs.nox_env == 0 }}
         run: nox ${{ inputs.nox_cmd }}
 
       - name: Run tests with nox and one input env
-        if: ${{ env.nox_env == 1 }}
+        if: ${{ inputs.nox_env == 1 }}
         run: nox ${{ inputs.nox_cmd }}
         env:
-          ${{ inputs.nox_env_name }}: ${{ secrets.NOX_ENV_VALUE }}
+          ${{ inputs.nox_env_1_name }}: ${{ secrets.NOX_ENV_1_VALUE }}
 
       - name: Run tests with nox and two input env
-        if: ${{ env.nox_env == 2 }}
+        if: ${{ inputs.nox_env == 2 }}
         run: nox ${{ inputs.nox_cmd }}
         env:
-          ${{ inputs.nox_env_name }}: ${{ secrets.NOX_ENV_VALUE }}
+          ${{ inputs.nox_env_1_name }}: ${{ secrets.NOX_ENV_1_VALUE }}
           ${{ inputs.nox_env_2_name }}: ${{ secrets.NOX_ENV_2_VALUE }}
 
-      - run: echo '${{ env.nox_env }}'
-
       - name: Run tests with nox and three input env
-        if: ${{ env.nox_env == 3 }}
+        if: ${{ inputs.nox_env == 3 }}
         run: nox ${{ inputs.nox_cmd }}
         env:
-          ${{ inputs.nox_env_name }}: ${{ secrets.NOX_ENV_VALUE }}
+          ${{ inputs.nox_env_1_name }}: ${{ secrets.NOX_ENV_1_VALUE }}
           ${{ inputs.nox_env_2_name }}: ${{ secrets.NOX_ENV_2_VALUE }}
           ${{ inputs.nox_env_3_name }}: ${{ secrets.NOX_ENV_3_VALUE }}
 
       - name: Run tests with nox and four input env
-        if: ${{ env.nox_env == 4 }}
+        if: ${{ inputs.nox_env == 4 }}
         run: nox ${{ inputs.nox_cmd }}
         env:
-          ${{ inputs.nox_env_name }}: ${{ secrets.NOX_ENV_VALUE }}
+          ${{ inputs.nox_env_1_name }}: ${{ secrets.NOX_ENV_1_VALUE }}
           ${{ inputs.nox_env_2_name }}: ${{ secrets.NOX_ENV_2_VALUE }}
           ${{ inputs.nox_env_3_name }}: ${{ secrets.NOX_ENV_3_VALUE }}
           ${{ inputs.nox_env_4_name }}: ${{ secrets.NOX_ENV_4_VALUE }}
-#
-#      - name: Tag and publish docker image to Google Cloud if built by nox
-#        if: ${{ inputs.nox_image }}
-#        run: |
-#          docker tag eu.gcr.io/digdir-fdk-infra/${{ inputs.app_name }}:test eu.gcr.io/digdir-fdk-infra/${{ inputs.app_name }}:${{ github.sha }}
-#          docker tag eu.gcr.io/digdir-fdk-infra/${{ inputs.app_name }}:test eu.gcr.io/digdir-fdk-infra/${{ inputs.app_name }}:${{ env.image_tag }}
-#          docker rmi eu.gcr.io/digdir-fdk-infra/${{ inputs.app_name }}:test
-#          docker -- push eu.gcr.io/digdir-fdk-infra/${{ inputs.app_name }} -a
-#
-#      - name: Build and push image if not handled by nox
-#        if: ${{ !inputs.nox_image }}
-#        id: docker_build
-#        uses: docker/build-push-action@v3
-#        with:
-#          context: ${{ inputs.dockerfile_context }}
-#          file: ${{ inputs.dockerfile }}
-#          push: true
-#          tags: ${{ steps.meta.outputs.tags }}
-#          labels: ${{ steps.meta.outputs.labels }}
-#          cache-from: type=local,src=.cache
-#          cache-to: type=local,dest=.cache
-#          build-args: |
-#            GITHUB_TOKEN=${{ secrets.GH_TOKEN }}
-#
-#      - name: Apply Helm template
-#        run: |
-#          helm repo add fdk https://informasjonsforvaltning.github.io/helm-chart/
-#          helm fetch --untar --untardir ./helm fdk/${{ inputs.app_name }}
-#          helm template --set DOCKER_IMAGE_NAME="eu.gcr.io/digdir-fdk-infra/${{ inputs.app_name }}:${{ github.sha }}" \
-#          -f ./helm/${{ inputs.app_name }}/values/${{ inputs.environment }}.yaml \
-#          ./helm/${{ inputs.app_name }}/ > ./kubectlapply.yaml
-#          chmod o+w ./kubectlapply.yaml
-#          cat kubectlapply.yaml
-#
-#      - name: Auth gcloud CLI for deploy
-#        uses: google-github-actions/auth@v0
-#        with:
-#          credentials_json: ${{ secrets.DIGDIR_FDK_AUTODEPLOY }}
-#
-#      - name: Create snapshot if needed
-#        if: ${{ inputs.snapshot_disk }}
-#        run: |
-#          gcloud compute --project ${{ inputs.cluster }} disks snapshot "${{ inputs.snapshot_disk }}" \
-#          --snapshot-names "${{ inputs.snapshot_name }}-${{ env.SHORT_SHA }}" --zone "${{ inputs.snapshot_zone }}" &
-#          wait
-#          gcloud compute --project ${{ inputs.cluster }} snapshots add-labels "${{ inputs.snapshot_name }}-${{ env.SHORT_SHA }}" \
-#          --labels="snapshotdays="14""
-#
-#      - name: Deploy to GCP & check status
-#        run: |
-#          gcloud container clusters get-credentials ${{ inputs.cluster }} --region europe-north1-a --project ${{ inputs.cluster }}
-#          kubectl apply -f ./kubectlapply.yaml --force
-#          if ! kubectl --namespace=${{ inputs.environment }} rollout status deployment ${{ inputs.app_name }}; then
-#            kubectl --namespace=${{ inputs.environment }} rollout undo deployment ${{ inputs.app_name }}
-#            kubectl --namespace=${{ inputs.environment }} rollout status deployment ${{ inputs.app_name }}
-#            exit 1
-#          fi
-#
-#      - name: Set slack message (if success)
-#        if: always() && job.status == 'success'
-#        run: |
-#          echo "slack_emoji=:white_check_mark:" >> $GITHUB_ENV
-#          echo "slack_text=Succeeded" >> $GITHUB_ENV
-#          echo "slack_color=#2eb886" >> $GITHUB_ENV
-#
-#      - name: Set slack message (if failure)
-#        if: always() && job.status == 'failure'
-#        run: |
-#          echo "slack_emoji=:no_entry:" >> $GITHUB_ENV
-#          echo "slack_text=Failed" >> $GITHUB_ENV
-#          echo "slack_color=#a30200" >> $GITHUB_ENV
-#
-#      - name: Notify all if failure in prod-workflow
-#        if: always() && job.status == 'failure' && inputs.environment == 'prod'
-#        run: echo "notify_all=@channel " >> $GITHUB_ENV
-#
-#      - name: Set slack message (if cancelled)
-#        if: always() && job.status == 'cancelled'
-#        run: |
-#          echo "slack_emoji=:warning:" >> $GITHUB_ENV
-#          echo "slack_text=Cancelled" >> $GITHUB_ENV
-#          echo "slack_color=#daa038" >> $GITHUB_ENV
-#
-#      - name: Notify slack
-#        id: slack
-#        uses: slackapi/slack-github-action@v1
-#        with:
-#          payload: |
-#            {
-#              "attachments": [
-#                {
-#                  "color": "${{ env.slack_color }}",
-#                  "blocks": [
-#                    {
-#                      "type": "section",
-#                      "text": {
-#                        "type": "mrkdwn",
-#                        "text": "${{ env.notify_all }}${{ env.slack_emoji }} ${{ env.slack_text }} GitHub Actions\n*Application:* ${{ inputs.app_name }}\n*Environment:* ${{ inputs.environment }}"
-#                      },
-#                      "fields": [
-#                        {
-#                            "type": "mrkdwn",
-#                            "text": "*commit:* \n<${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }} | ${{ env.SHORT_SHA }} >"
-#                        },
-#                        {
-#                            "type": "mrkdwn",
-#                            "text": "*author:* \n${{ github.actor }}"
-#                        },
-#                        {
-#                            "type": "mrkdwn",
-#                            "text": "*workflow:* \n<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} | ${{ github.workflow }}>"
-#                        },
-#                        {
-#                            "type": "mrkdwn",
-#                            "text": "*${{ env.event_text }}:* \n<${{ github.server_url }}/${{ github.repository }}/${{ env.event_path }} | ${{ env.event_name }}>"
-#                        }
-#                      ]
-#                    }
-#                  ]
-#                }
-#              ]
-#            }
-#        env:
-#          SLACK_WEBHOOK_URL: ${{ env.slack_webhook }}
-#          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
-#        if: always()
+
+      - name: Tag and publish docker image to Google Cloud if built by nox
+        if: ${{ inputs.nox_image }}
+        run: |
+          docker tag eu.gcr.io/digdir-fdk-infra/${{ inputs.app_name }}:test eu.gcr.io/digdir-fdk-infra/${{ inputs.app_name }}:${{ github.sha }}
+          docker tag eu.gcr.io/digdir-fdk-infra/${{ inputs.app_name }}:test eu.gcr.io/digdir-fdk-infra/${{ inputs.app_name }}:${{ env.image_tag }}
+          docker rmi eu.gcr.io/digdir-fdk-infra/${{ inputs.app_name }}:test
+          docker -- push eu.gcr.io/digdir-fdk-infra/${{ inputs.app_name }} -a
+
+      - name: Build and push image if not handled by nox
+        if: ${{ !inputs.nox_image }}
+        id: docker_build
+        uses: docker/build-push-action@v3
+        with:
+          context: ${{ inputs.dockerfile_context }}
+          file: ${{ inputs.dockerfile }}
+          push: true
+          tags: ${{ steps.meta.outputs.tags }}
+          labels: ${{ steps.meta.outputs.labels }}
+          cache-from: type=local,src=.cache
+          cache-to: type=local,dest=.cache
+          build-args: |
+            GITHUB_TOKEN=${{ secrets.GH_TOKEN }}
+
+      - name: Apply Helm template
+        run: |
+          helm repo add fdk https://informasjonsforvaltning.github.io/helm-chart/
+          helm fetch --untar --untardir ./helm fdk/${{ inputs.app_name }}
+          helm template --set DOCKER_IMAGE_NAME="eu.gcr.io/digdir-fdk-infra/${{ inputs.app_name }}:${{ github.sha }}" \
+          -f ./helm/${{ inputs.app_name }}/values/${{ inputs.environment }}.yaml \
+          ./helm/${{ inputs.app_name }}/ > ./kubectlapply.yaml
+          chmod o+w ./kubectlapply.yaml
+          cat kubectlapply.yaml
+
+      - name: Auth gcloud CLI for deploy
+        uses: google-github-actions/auth@v0
+        with:
+          credentials_json: ${{ secrets.DIGDIR_FDK_AUTODEPLOY }}
+
+      - name: Create snapshot if needed
+        if: ${{ inputs.snapshot_disk }}
+        run: |
+          gcloud compute --project ${{ inputs.cluster }} disks snapshot "${{ inputs.snapshot_disk }}" \
+          --snapshot-names "${{ inputs.snapshot_name }}-${{ env.SHORT_SHA }}" --zone "${{ inputs.snapshot_zone }}" &
+          wait
+          gcloud compute --project ${{ inputs.cluster }} snapshots add-labels "${{ inputs.snapshot_name }}-${{ env.SHORT_SHA }}" \
+          --labels="snapshotdays="14""
+
+      - name: Deploy to GCP & check status
+        run: |
+          gcloud container clusters get-credentials ${{ inputs.cluster }} --region europe-north1-a --project ${{ inputs.cluster }}
+          kubectl apply -f ./kubectlapply.yaml --force
+          if ! kubectl --namespace=${{ inputs.environment }} rollout status deployment ${{ inputs.app_name }}; then
+            kubectl --namespace=${{ inputs.environment }} rollout undo deployment ${{ inputs.app_name }}
+            kubectl --namespace=${{ inputs.environment }} rollout status deployment ${{ inputs.app_name }}
+            exit 1
+          fi
+
+      - name: Set slack message (if success)
+        if: always() && job.status == 'success'
+        run: |
+          echo "slack_emoji=:white_check_mark:" >> $GITHUB_ENV
+          echo "slack_text=Succeeded" >> $GITHUB_ENV
+          echo "slack_color=#2eb886" >> $GITHUB_ENV
+
+      - name: Set slack message (if failure)
+        if: always() && job.status == 'failure'
+        run: |
+          echo "slack_emoji=:no_entry:" >> $GITHUB_ENV
+          echo "slack_text=Failed" >> $GITHUB_ENV
+          echo "slack_color=#a30200" >> $GITHUB_ENV
+
+      - name: Notify all if failure in prod-workflow
+        if: always() && job.status == 'failure' && inputs.environment == 'prod'
+        run: echo "notify_all=@channel " >> $GITHUB_ENV
+
+      - name: Set slack message (if cancelled)
+        if: always() && job.status == 'cancelled'
+        run: |
+          echo "slack_emoji=:warning:" >> $GITHUB_ENV
+          echo "slack_text=Cancelled" >> $GITHUB_ENV
+          echo "slack_color=#daa038" >> $GITHUB_ENV
+
+      - name: Notify slack
+        id: slack
+        uses: slackapi/slack-github-action@v1
+        with:
+          payload: |
+            {
+              "attachments": [
+                {
+                  "color": "${{ env.slack_color }}",
+                  "blocks": [
+                    {
+                      "type": "section",
+                      "text": {
+                        "type": "mrkdwn",
+                        "text": "${{ env.notify_all }}${{ env.slack_emoji }} ${{ env.slack_text }} GitHub Actions\n*Application:* ${{ inputs.app_name }}\n*Environment:* ${{ inputs.environment }}"
+                      },
+                      "fields": [
+                        {
+                            "type": "mrkdwn",
+                            "text": "*commit:* \n<${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }} | ${{ env.SHORT_SHA }} >"
+                        },
+                        {
+                            "type": "mrkdwn",
+                            "text": "*author:* \n${{ github.actor }}"
+                        },
+                        {
+                            "type": "mrkdwn",
+                            "text": "*workflow:* \n<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} | ${{ github.workflow }}>"
+                        },
+                        {
+                            "type": "mrkdwn",
+                            "text": "*${{ env.event_text }}:* \n<${{ github.server_url }}/${{ github.repository }}/${{ env.event_path }} | ${{ env.event_name }}>"
+                        }
+                      ]
+                    }
+                  ]
+                }
+              ]
+            }
+        env:
+          SLACK_WEBHOOK_URL: ${{ env.slack_webhook }}
+          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
+        if: always()
